# Generated by Django 3.1.2 on 2020-12-24 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201222_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='bundle_type',
            field=models.CharField(blank=True, choices=[('article', 'Article'), ('thesis', 'Thesis'), ('book', 'Book'), ('report', 'Report'), ('misc', 'Misc')], max_length=10, null=True),
        ),
    ]
