# Generated by Django 3.1.2 on 2020-12-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_bundle_bundle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='origin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
