# Generated by Django 3.1.2 on 2020-12-26 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_bundle_origin_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
