# Generated by Django 3.1.2 on 2020-12-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='claps',
        ),
        migrations.DeleteModel(
            name='Clap',
        ),
    ]
