# Generated by Django 3.1.2 on 2020-12-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='interest_id',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Science'), (1, 'Maths'), (2, 'Computer'), (3, 'History'), (4, 'Health')], primary_key=True, serialize=False),
        ),
    ]
