# Generated by Django 3.1.2 on 2020-11-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201127_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='current_status',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('teacher', 'Teacher'), ('none', 'Prefer no to say')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='interested_fields',
            field=models.CharField(blank=True, choices=[('science', 'Science'), ('maths', 'Maths'), ('computer', 'Computer'), ('history', 'History'), ('health', 'Health')], max_length=10, null=True),
        ),
    ]
