# Generated by Django 3.1.2 on 2020-12-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201128_1451'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReceiveAuthorshipRequest',
            new_name='AcceptedAuthorshipRequest',
        ),
        migrations.RenameModel(
            old_name='SubmitAuthorshipRequest',
            new_name='ReceivedAuthorshipRequest',
        ),
    ]
