# Generated by Django 3.1.2 on 2020-12-19 05:22

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('profiles', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivedauthorshiprequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_profile', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='fork',
            name='bundle_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fork_origin', to='events.bundle'),
        ),
        migrations.AddField(
            model_name='fork',
            name='bundle_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forked_into', to='events.bundle'),
        ),
        migrations.AddField(
            model_name='comment',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='events.bundle'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_profile', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='clap',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle', to='events.bundle'),
        ),
        migrations.AddField(
            model_name='clap',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='claps',
            field=models.ManyToManyField(blank=True, related_name='bundle_liked', through='events.Clap', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='co_authors',
            field=models.ManyToManyField(related_name='cocreators', through='events.AcceptedAuthorshipRequest', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='co_authors_request',
            field=models.ManyToManyField(related_name='creatorrequests', through='events.ReceivedAuthorshipRequest', to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_creator', to='profiles.profile'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='fork',
            field=models.ManyToManyField(related_name='forks', through='events.Fork', to='events.Bundle'),
        ),
        migrations.AddField(
            model_name='bundle',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='acceptedauthorshiprequest',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_bundle', to='events.bundle'),
        ),
        migrations.AddField(
            model_name='acceptedauthorshiprequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accepted_profile', to='profiles.profile'),
        ),
    ]
