# Generated by Django 3.1.2 on 2020-11-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201111_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bundle',
            old_name='creation_on',
            new_name='created_on',
        ),
    ]
