# Generated by Django 3.1.2 on 2020-11-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20201123_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bundle',
            options={'ordering': ('-published_on', 'title', 'context')},
        ),
    ]
