# Generated by Django 3.1.2 on 2020-11-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201122_1427'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bundle',
            managers=[
            ],
        ),
    ]
