# Generated by Django 3.1.2 on 2020-12-18 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201128_1451'),
        ('events', '0003_auto_20201218_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorshiprequestbase',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.bundle'),
        ),
        migrations.AlterField(
            model_name='authorshiprequestbase',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='co_authors',
            field=models.ManyToManyField(related_name='cocreators', through='events.AcceptedAuthorshipRequest', to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='bundle',
            name='co_authors_request',
            field=models.ManyToManyField(related_name='creatorrequests', through='events.ReceivedAuthorshipRequest', to='profiles.Profile'),
        ),
    ]
