# Generated by Django 3.1.2 on 2020-11-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201127_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='bundle_papers/%Y/%m/%d/'),
        ),
    ]
