# Generated by Django 3.1.2 on 2020-11-22 09:12

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('events', '0004_auto_20201122_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
