# Generated by Django 3.1.2 on 2020-11-29 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20201129_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='git_url',
            field=models.URLField(blank=True),
        ),
    ]
