# Generated by Django 3.1.2 on 2020-12-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201128_1451'),
        ('events', '0006_bundle_git_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='bundle_liked', to='profiles.Profile'),
        ),
    ]
