# Generated by Django 3.1.2 on 2020-12-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20201203_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='claps',
        ),
    ]
