# Generated by Django 3.1.2 on 2020-12-03 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201128_1451'),
        ('events', '0009_remove_bundle_claps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claped_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle', to='events.bundle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='profiles.profile')),
            ],
            options={
                'ordering': ('-claped_on',),
            },
        ),
        migrations.AddField(
            model_name='bundle',
            name='claps',
            field=models.ManyToManyField(blank=True, related_name='bundle_liked', through='events.Clap', to='profiles.Profile'),
        ),
    ]
