# Generated by Django 3.1.2 on 2020-12-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_eventbase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventBase',
        ),
    ]
