# Generated by Django 3.1.2 on 2020-12-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20201128_1451'),
        ('events', '0012_delete_eventbase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_creator', to='profiles.profile'),
        ),
    ]
