# Generated by Django 3.1.2 on 2020-12-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20201218_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='forkable',
            field=models.BooleanField(default=True),
        ),
    ]
