# Generated by Django 3.1.2 on 2020-12-18 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_bundle_forkable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='forkable',
        ),
    ]
