# Generated by Django 3.1.2 on 2020-12-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_bundle_forkable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bundle',
            name='fork',
        ),
        migrations.AddField(
            model_name='bundle',
            name='forkable',
            field=models.BooleanField(default=True),
        ),
    ]
