# Generated by Django 3.1.2 on 2020-12-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20201218_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='bundle',
            name='fork',
            field=models.ManyToManyField(related_name='forks', through='events.Fork', to='events.Bundle'),
        ),
    ]
