# Generated by Django 3.1.2 on 2020-11-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='action',
            old_name='target_ct',
            new_name='target_contenttype',
        ),
    ]
