# Generated by Django 3.1.2 on 2020-12-24 16:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_profile_contact_email'),
        ('events', '0004_bundle_origin_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bundles', models.ManyToManyField(to='events.Bundle')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readinglist_creator', to='profiles.profile')),
            ],
        ),
    ]
