# Generated by Django 3.1.2 on 2020-12-25 05:40

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_bundle_origin_url'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('profiles', '0003_profile_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('bundles', models.ManyToManyField(to='events.Bundle')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readinglist_creator', to='profiles.profile')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
