# Generated by Django 3.1.2 on 2020-12-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_bundle_origin_url'),
        ('services', '0002_readinglist_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='bundles',
            field=models.ManyToManyField(null=True, to='events.Bundle'),
        ),
    ]
