# Generated by Django 3.1.2 on 2020-12-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_bundle_origin_url'),
        ('services', '0003_auto_20201224_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglist',
            name='bundles',
            field=models.ManyToManyField(to='events.Bundle'),
        ),
    ]
