# Generated by Django 3.1.2 on 2020-12-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20201224_2346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinglist',
            options={'ordering': ['-created_on']},
        ),
    ]
