# Generated by Django 3.1.2 on 2020-12-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_sharescount_viewscount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharescount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='viewscount',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
