name: Patralaya

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run: |
        python manage.py migrate
        python manage.py makemigrations
        python manage.py migrate
    - name: Deploy to Heroku
      env:
        HOST_NAME: ${{ secrets.HOST_NAME }}
        AUTH_KEY: ${{ secrets.AUTH_KEY }}
      if: github.ref == 'refs/heads/master' && job.status == 'success'
      run: |
        git remote add heroku https://heroku:$AUTH_KEY@git.heroku.com/$HOSTNAME.git
        git push heroku HEAD:master -f
      
